name: 安装musl
run-name: 安装musl
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: pwd
      - run: git clone https://github.com/richfelker/musl-cross-make.git
      - run: pwd
      - run: ls
      - run: sleep 3
      - run: cd ./musl-cross-make
      - run: pwd
      - run: ls
      - run: make TARGET=x86_64-linux-musl
      - run: musl-gcc -v

